name: 05 - 2 - Event Filters - Activity Types

on: 
    pull_request:
        types:
            - opened
        branches:
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow runs on pull request is closed."